[project]
name = "rl-mujoco-inverted-pendulum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "torch>=2.7.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
